#!/bin/sh

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# determine the verison
AVAILABLE_VERSION=$(curl -s https://geo.mirror.pkgbuild.com/iso/latest/arch/version)

if [ ! $(ls /boot/live | grep $AVAILABLE_VERSION) ]; then
  echo "You are already on the latest version"
  exit
fi

ARCH_ISO="archlinux-$AVAILABLE_VERSION-x86_64.iso"
echo "Downloading the latest version of Arch Linux $ARCH_ISO"
# # download the iso
# curl -o /tmp/archlinux-$AVAILABLE_VERSION-x86_64.iso https://geo.mirror.pkgbuild.com/iso/latest/archlinux-$AVAILABLE_VERSION-x86_64.iso
#
# # check the download against the sha
# echo $AVAILABLE_SHA_VERSION | sha256sum --check  
